import { boundary } from "@shopify/shopify-app-react-router/server";
import { authenticate } from "../shopify.server";

// 生成llms.txt内容的函数
async function generateLlmsContent(session) {
  const { admin } = await authenticate.admin(session);

  try {
    // 获取店铺信息
    const shopResponse = await admin.graphql(
      `#graphql
      query {
        shop {
          url
        }
      }`
    );
    const shopData = await shopResponse.json();
    const shopUrl = shopData.data.shop.url;

    // 获取产品列表
    const productsResponse = await admin.graphql(
      `#graphql
      query {
        products(first: 100) {
          edges {
            node {
              handle
              onlineStoreUrl
            }
          }
        }
      }`
    );
    const productsData = await productsResponse.json();

    // 获取集合列表
    const collectionsResponse = await admin.graphql(
      `#graphql
      query {
        collections(first: 100) {
          edges {
            node {
              handle
              onlineStoreUrl
            }
          }
        }
      }`
    );
    const collectionsData = await collectionsResponse.json();

    // 获取页面列表
    const pagesResponse = await admin.graphql(
      `#graphql
      query {
        pages(first: 100) {
          edges {
            node {
              handle
              url
            }
          }
        }
      }`
    );
    const pagesData = await pagesResponse.json();

    // 收集所有URL
    const urls = [];

    // 添加产品URL
    if (productsData.data?.products?.edges) {
      productsData.data.products.edges.forEach(edge => {
        if (edge.node.onlineStoreUrl) {
          urls.push(edge.node.onlineStoreUrl);
        }
      });
    }

    // 添加集合URL
    if (collectionsData.data?.collections?.edges) {
      collectionsData.data.collections.edges.forEach(edge => {
        if (edge.node.onlineStoreUrl) {
          urls.push(edge.node.onlineStoreUrl);
        }
      });
    }

    // 添加页面URL
    if (pagesData.data?.pages?.edges) {
      pagesData.data.pages.edges.forEach(edge => {
        if (edge.node.url) {
          urls.push(edge.node.url);
        }
      });
    }

    // 过滤掉不应该包含的路径
    const filteredUrls = urls.filter(url => {
      return !url.includes('/cart') &&
             !url.includes('/checkout') &&
             !url.includes('/account');
    });

    // 生成llms.txt内容
    let content = `# LLMs.txt for AI Indexing\n`;
    content += `# Generated by IndexGPT on ${new Date().toISOString()}\n\n`;
    content += `Sitemap: ${shopUrl}/sitemap.xml\n\n`;
    content += `Allow: /products/\n`;
    content += `Allow: /collections/\n`;
    content += `Allow: /pages/\n\n`;
    content += `Disallow: /cart/\n`;
    content += `Disallow: /checkout/\n`;
    content += `Disallow: /account/\n\n`;

    // 添加URL列表
    filteredUrls.forEach(url => {
      content += `${url}\n`;
    });

    return {
      success: true,
      content: content,
      urlCount: filteredUrls.length,
      lastGenerated: new Date().toISOString()
    };
  } catch (error) {
    console.error("Error generating llms.txt:", error);
    return {
      success: false,
      error: error.message
    };
  }
}

// 手动生成llms.txt的API端点
export const action = async ({ request }) => {
  const { session } = await authenticate.admin(request);

  const result = await generateLlmsContent(session);

  if (result.success) {
    return new Response(JSON.stringify({
      success: true,
      message: "llms.txt generated successfully",
      urlCount: result.urlCount,
      lastGenerated: result.lastGenerated
    }), {
      status: 200,
      headers: { "Content-Type": "application/json" }
    });
  } else {
    return new Response(JSON.stringify({
      success: false,
      message: "Failed to generate llms.txt",
      error: result.error
    }), {
      status: 500,
      headers: { "Content-Type": "application/json" }
    });
  }
};

export const headers = (headersArgs) => {
  return boundary.headers(headersArgs);
};