import { boundary } from "@shopify/shopify-app-react-router/server";
import prisma from "../db.server";

// 生成llms.txt内容的函数
async function generateLlmsContent(shopDomain, accessToken) {
  // 注意：在实际实现中，这里需要使用Shopify Admin API来获取数据
  // 由于这是公共路由，我们无法直接使用authenticate.admin
  // 需要从数据库获取access token然后调用API

  try {
    // 从数据库获取店铺信息
    const shop = await prisma.shop.findUnique({
      where: { shopDomain: shopDomain }
    });

    if (!shop) {
      return {
        success: false,
        error: "Shop not found"
      };
    }

    // 在实际实现中，这里会使用accessToken调用Shopify API获取数据
    // 为简化起见，我们返回示例内容

    const content = `# LLMs.txt for AI Indexing
# Generated by IndexGPT

Sitemap: https://${shopDomain}/sitemap.xml

Allow: /products/
Allow: /collections/
Allow: /pages/

Disallow: /cart/
Disallow: /checkout/
Disallow: /account/

# Product URLs
https://${shopDomain}/products/example-product-1
https://${shopDomain}/products/example-product-2

# Collection URLs
https://${shopDomain}/collections/all
https://${shopDomain}/collections/featured

# Page URLs
https://${shopDomain}/pages/about-us
https://${shopDomain}/pages/contact

# Last Generated: ${new Date().toISOString()}
`;

    return {
      success: true,
      content: content
    };
  } catch (error) {
    console.error("Error generating llms.txt:", error);
    return {
      success: false,
      error: error.message
    };
  }
}

// 公开访问的llms.txt端点
export const loader = async ({ request }) => {
  const url = new URL(request.url);
  const host = url.host; // 获取店铺域名

  // 生成llms.txt内容
  const result = await generateLlmsContent(host, null);

  if (result.success) {
    return new Response(result.content, {
      status: 200,
      headers: {
        "Content-Type": "text/plain",
        "Cache-Control": "public, max-age=300" // 5分钟缓存
      }
    });
  } else {
    return new Response("Error generating llms.txt", {
      status: 500,
      headers: { "Content-Type": "text/plain" }
    });
  }
};

export const headers = (headersArgs) => {
  return boundary.headers(headersArgs);
};